### ISSUE TITLE
关于hgt模型在dblp数据集上运行问题

### ISSUE THREAD

**Issue by liujing1023** [ZZy979/pytorch-tutorial#1]
您好，我看到您复现了hgt模型在acm和imdb数据集上的实验结果，想问您有没有复现在dblp这个数据集上的结果呀，可以发我看看嘛？我用您的代码通过直接调用您处理好的dblp数据集（from gnn.data import DBLPFourAreaDataset），但是发现在您代码的23行报以下错误：
File "hgt.py", line 24, in train
    features = {ntype: g.nodes[ntype].data['feat'] for ntype in g.ntypes} 
  File "hgt.py", line 24, in <dictcomp>
    features = {ntype: g.nodes[ntype].data['feat'] for ntype in g.ntypes} 
  File "/home/lj/anaconda3/envs/dgl/lib/python3.6/site-packages/dgl/view.py", line 66, in __getitem__
    return self._graph._get_n_repr(self._ntid, self._nodes)[key]
  File "/home/lj/anaconda3/envs/dgl/lib/python3.6/site-packages/dgl/frame.py", line 393, in __getitem__
    return self._columns[name].data
KeyError: 'feat'
不知道这个错误您有没有遇到，想问下您怎么解决，谢谢~

**Comment by ZZy979** [comment]
没有复现DBLP数据集的结果，因为这个数据集只有author顶点有输入特征，而HGT模型要求所有类型的顶点都有输入特征，ACM和IMDb数据集都满足这一条件（见`ACMDataset`和`IMDbDataset`的文档字符串说明）

要在DBLP数据集上训练HGT模型需要为其他三种类型的顶点补充输入特征，有两种方式：
1. 人工构造，例如paper顶点特征是关联的author顶点特征的平均、conf和term顶点特征是one-hot编码，ACM数据集就使用了这种方式（见 https://github.com/ZZy979/pytorch-tutorial/blob/master/gnn/data/acm.py#L117 ）
2. 使用metapath2vec等方式预训练顶点嵌入（见 https://github.com/ZZy979/pytorch-tutorial/tree/master/gnn/metapath2vec ）

**Comment by liujing1023** [comment]
> 没有复现DBLP数据集的结果，因为这个数据集只有author顶点有输入特征，而HGT模型要求所有类型的顶点都有输入特征，ACM和IMDb数据集都满足这一条件（见`ACMDataset`和`IMDbDataset`的文档字符串说明）
> 
> 要在DBLP数据集上训练HGT模型需要为其他三种类型的顶点补充输入特征，有两种方式：
> 
> 1. 人工构造，例如paper顶点特征是关联的author顶点特征的平均、conf和term顶点特征是one-hot编码，ACM数据集就使用了这种方式（见 https://github.com/ZZy979/pytorch-tutorial/blob/master/gnn/data/acm.py#L117 ）
> 2. 使用metapath2vec等方式预训练顶点嵌入（见 https://github.com/ZZy979/pytorch-tutorial/tree/master/gnn/metapath2vec ）

哇，谢谢。我刚才试了试您说的第一个方法，我直接在dblp的这行(https://github.com/ZZy979/pytorch-tutorial/blob/master/gnn/data/dblp.py#L174)代码下直接添加了如下代码：
        # paper顶点特征是关联的author顶点特征的平均
        self.g.multi_update_all({'pa': (fn.copy_u('feat', 'm'), fn.mean('m', 'feat'))}, 'sum')
        #conf和term顶点特征是one-hot编码
        self.g.nodes['conf'].data['feat'] = torch.eye(self.g.num_nodes('conf'))
        self.g.nodes['term'].data['feat'] = torch.eye(self.g.num_nodes('term'))
但是依旧报和上面一样的错误。您可以再帮我看下怎么解决吗？如果方便的话可以加下您微信吗，我的微信是LiujingScorpio

**Comment by ZZy979** [comment]
先删除~/.dgl/DBLP_four_area/DBLP_four_area_dgl_graph.bin再重新运行，因为`DGLDataset`默认直接加载缓存的图

另外计算paper顶点特征应该是`self.g.multi_update_all({'ap': (fn.copy_u('feat', 'm'), fn.mean('m', 'feat'))}, 'sum')`，这样才是从author向paper传递

**Comment by liujing1023** [comment]
> 先删除~/.dgl/DBLP_four_area/DBLP_four_area_dgl_graph.bin再重新运行，因为`DGLDataset`默认直接加载缓存的图
> 
> 另外计算paper顶点特征应该是`self.g.multi_update_all({'ap': (fn.copy_u('feat', 'm'), fn.mean('m', 'feat'))}, 'sum')`，这样才是从author向paper传递

多谢大佬，代码已经跑通~
