### ISSUE TITLE
RuntimeError: Bool type is not supported by dlpack

### ISSUE THREAD

**Issue by lavender86** [ZZy979/pytorch-tutorial#2]
您好！
      我最近也在学习HAN这篇文章，看到了您的代码，就想着跟着复现一下，但是我在运行的时候有一个错误“RuntimeError: Bool type is not supported by dlpack”，我不懂这个是什么意思，百度查了好久也没有搞明白是干嘛的，所以想跟您请教一下
”

**Comment by ZZy979** [comment]
能发一下完整的错误信息吗，另外确认一下PyTorch和DGL版本与requirements.txt中的是否一致

**Comment by lavender86** [comment]
您好！
&nbsp; &nbsp; &nbsp; 根据您的指导，我确认了一下版本信息，然后重装了一下，能够跑通了，非常感谢您！！！
&nbsp; &nbsp; &nbsp; 但我是只能跑DATASET数据集，不能跑HETERO_DATASET数据集，是在train.py报错，“AttributeError: module 'data.dgl' has no attribute 'metapath_reachable_graph'”，我现在的pytorch是1.10.0，DGL是0.7.2版本的，您可以再帮我看一看吗







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZZy979/pytorch-tutorial"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月27日(星期六) 中午11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZZy979/pytorch-tutorial] RuntimeError: Bool type is not supported by dlpack (Issue #2)





 
能发一下完整的错误信息吗，另外确认一下PyTorch和DGL版本与requirements.txt中的是否一致
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZZy979** [comment]
> AttributeError: module 'data.dgl' has no attribute 'metapath_reachable_graph'

确认是我代码的问题，因为之前增加了`gnn.data.dgl`模块，train.py中又使用了`from gnn.data import *`，导致导入的`dgl`这个名字变成了我自己的模块，感谢你帮我发现这个bug。

已修复，在我的电脑上测试没有问题了，你可以再试一下。

**Comment by lavender86** [comment]
感谢大佬！！可以跑了，，只不过在跑dblp数据集的时候数值一直不变化，“Epoch 199 | Train Loss 1.3732 | Train Micro-F1 0.3063 | Train Macro-F1 0.1172 | Val Micro-F1 0.2775 | Val Macro-F1 0.1086”一直是这个
不知道您那边是这样吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZZy979/pytorch-tutorial"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZZy979/pytorch-tutorial] RuntimeError: Bool type is not supported by dlpack (Issue #2)





  
AttributeError: module 'data.dgl' has no attribute 'metapath_reachable_graph'
  
确认是我代码的问题，因为之前增加了gnn.data.dgl模块，train.py中又使用了from gnn.data import *，导致导入的dgl这个名字变成了我自己的模块，感谢你帮我发现这个bug。
 
已修复，在我的电脑上测试没有问题了，你可以再试一下。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZZy979** [comment]
我这边测试是正常的
```
Epoch 199 | Train Loss 0.1028 | Train Micro-F1 0.9700 | Train Macro-F1 0.9687 | Val Micro-F1 0.9425 | Val Macro-F1 0.9383
Test Micro-F1 0.9247 | Test Macro-F1 0.9183
```

可能是你升级了DGL版本之后数据集没有重新构造的问题
尝试删除~/.dgl/DBLP_four_area/DBLP_four_area_dgl_graph.bin文件之后再重新运行

**Comment by lavender86** [comment]
噢噢好嘞好嘞，估计就是我这边的问题，我再试一下，谢谢大佬！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZZy979/pytorch-tutorial"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 中午11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZZy979/pytorch-tutorial] RuntimeError: Bool type is not supported by dlpack (Issue #2)





 
我这边测试是正常的
 Epoch 199 | Train Loss 0.1028 | Train Micro-F1 0.9700 | Train Macro-F1 0.9687 | Val Micro-F1 0.9425 | Val Macro-F1 0.9383 Test Micro-F1 0.9247 | Test Macro-F1 0.9183  
可能是你升级了DGL版本之后数据集没有重新构造的问题
 尝试删除~/.dgl/DBLP_four_area/DBLP_four_area_dgl_graph.bin文件之后再重新运行
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
