### ISSUE TITLE
HetGNN 数据说明

### ISSUE THREAD

**Issue by mgao97** [ZZy979/pytorch-tutorial#3]
您好，看到您复现和简化了HetGNN原始代码，有几个问题想请教下：1. 代码可否改写为端到端方式？2.https://github.com/ZZy979/pytorch-tutorial/tree/master/gnn/hetgnn请问readme.md中的corpus.txt文件指的是什么文件？可否提供链接？感谢！
![image](https://user-images.githubusercontent.com/90015105/188914556-69d7e2ee-46e4-439a-9a2e-f06cc6ff2d23.png)

**Comment by ZZy979** [comment]
1. 改成端到端的方式比较困难，因为必须先做预训练顶点嵌入和生成邻居图这两个预处理步骤，这是模型结构决定的，而且生成邻居图的代码是严重依赖于图结构的，换一个数据集还要重新写这里的代码，所以这个模型的通用性比较差
2. corpus.txt是输出文件名，用来保存随机游走的结果，代码用到的数据文件都是作者提供的

**Comment by mgao97** [comment]
get，thanks a lot!👍



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月11日(周日) 下午5:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZZy979/pytorch-tutorial] HetGNN 数据说明 (Issue #3)




 
Closed #3 as completed.

**Comment by mgao97** [comment]
收到，非常感谢🙏




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZZy979/pytorch-tutorial"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月8日(星期四) 凌晨0:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZZy979/pytorch-tutorial] HetGNN 数据说明 (Issue #3)





  
改成端到端的方式比较困难，因为必须先做预训练顶点嵌入和生成邻居图这两个预处理步骤，这是模型结构决定的，而且生成邻居图的代码是严重依赖于图结构的，换一个数据集还要重新写这里的代码，所以这个模型的通用性比较差
 
corpus.txt是输出文件名，用来保存随机游走的结果，代码用到的数据文件都是作者提供的
